project:
  type: website
  output-dir: docs
  
website:
  title: "Merrick Osborne's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - collaborators.qmd
      - CV.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/MerrickOsbornePhD/OsborneMerrickProfessorWebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Merrick Osborne"

format:
  html:
    theme: simplex
    toc: false

editor: source

